"""
Base Strategy Class - Abstract base for all trading strategies.

All strategies inherit from BaseStrategy and implement the generate_signal method.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional, Dict, Any
from decimal import Decimal

from trading_bot.src.core.models import CandleData, TechnicalIndicators, TradeSignal, MarketCondition
from trading_bot.src.utils.logger import get_logger

# Import comprehensive debugging utilities
from trading_bot.src.utils.debug_utils import (
    debug_tracker, debug_line, debug_variable, debug_context, 
    debug_performance, debug_data_flow, debug_api_call, 
    debug_trade_decision, debug_strategy_execution, debug_risk_calculation,
    debug_indicator_calculation, debug_backtest_step, debug_entry_point,
    debug_exit_point, debug_conditional, debug_loop_iteration,
    get_debug_summary, export_debug_report
)


@dataclass
class StrategySignal:
    """
    Signal generated by a trading strategy.
    
    Attributes:
        signal: BUY, SELL, or HOLD
        confidence: Confidence level (0.0-1.0)
        strength: Signal strength (0.0-1.0)
        reasoning: Human-readable explanation
        entry_price: Recommended entry price
        stop_loss: Recommended stop loss price
        take_profit: Recommended take profit price
        metadata: Additional strategy-specific data
    """
    signal: TradeSignal
    confidence: float
    strength: float
    reasoning: str
    entry_price: Optional[Decimal] = None
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    metadata: Dict[str, Any] = None
    
    @debug_line

    
    def __post_init__(self):
        if self.metadata is None:
            self.metadata = {}
        
        # Validate confidence and strength
        assert 0.0 <= self.confidence <= 1.0, f"Confidence must be 0-1, got {self.confidence}"
        assert 0.0 <= self.strength <= 1.0, f"Strength must be 0-1, got {self.strength}"


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    All strategies must implement:
    - generate_signal(): Core signal generation logic
    - is_applicable(): Check if strategy applies to current market condition
    """
    
    @debug_line

    
    def __init__(self, name: str, strategy_type: str, config: Dict[str, Any]):
        """
        Initialize strategy.
        
        Args:
            name: Strategy name (e.g., "Fast_EMA_Cross_M5")
            strategy_type: Strategy type (trend_momentum, mean_reversion, etc.)
            config: Strategy configuration from trading_config.yaml
        """
        self.name = name
        self.strategy_type = strategy_type
        self.config = config
        
        # Core settings
        self.allocation = config.get('allocation', 5)
        self.min_confidence = config.get('min_confidence', 0.6)
        self.conditions = config.get('conditions', [])
        self.timeframes = config.get('timeframes', ['M5'])
        self.parameters = config.get('parameters', {})
        self.hold_time_override = config.get('hold_time_override', None)
        self.active_hours = config.get('active_hours', None)
        
        # Logger
        self.logger = get_logger(f"{__name__}.{name}")
        
        # Performance tracking
        self.signals_generated = 0
        self.signals_accepted = 0
        
    @abstractmethod
    async def generate_signal(
        self,
        candles: List[CandleData],
        indicators: TechnicalIndicators,
        market_condition: MarketCondition,
        current_time: Optional[datetime] = None
    ) -> Optional[StrategySignal]:
        """
        Generate trading signal based on strategy logic.
        
        Args:
            candles: List of candle data (most recent last)
            indicators: Pre-calculated technical indicators
            market_condition: Current market condition
            current_time: Current time (for session-based strategies)
            
        Returns:
            StrategySignal if conditions met, None otherwise
        """
        pass
    
    def is_applicable(self, market_condition: MarketCondition) -> bool:
        """
        Check if strategy is applicable for current market condition.
        
        Args:
            market_condition: Current market condition
            
        Returns:
            True if strategy should be evaluated
        """
        if not self.conditions:
            return True
        
        if 'ALL' in self.conditions:
            return True
            
        return market_condition.value in self.conditions
    
    def is_active_now(self, current_time: Optional[datetime] = None) -> bool:
        """
        Check if strategy is active during current time (for session-based strategies).
        
        Args:
            current_time: Current time (UTC)
            
        Returns:
            True if strategy is active
        """
        if not self.active_hours:
            return True
        
        if current_time is None:
            return True
        
        # Parse active hours (e.g., ["08:00-12:00", "13:00-17:00"])
        current_hour_min = current_time.strftime("%H:%M")
        
        for time_range in self.active_hours:
            if '-' in time_range:
                start, end = time_range.split('-')
                if start <= current_hour_min <= end:
                    return True
        
        return False
    
    def validate_signal(self, signal: StrategySignal) -> bool:
        """
        Validate that signal meets minimum requirements.
        
        Args:
            signal: Generated signal
            
        Returns:
            True if signal passes validation
        """
        # Check minimum confidence
        if signal.confidence < self.min_confidence:
            self.logger.debug(
                f"Signal rejected: confidence {signal.confidence:.2f} < {self.min_confidence:.2f}"
            )
            return False
        
        # Check that entry/stop/target are set for BUY/SELL signals
        if signal.signal in [TradeSignal.BUY, TradeSignal.SELL]:
            if signal.entry_price is None:
                self.logger.warning(f"Signal missing entry_price")
                return False
        
        return True
    
    def get_risk_reward_ratio(self, signal: StrategySignal) -> Optional[float]:
        """
        Calculate risk-reward ratio for a signal.
        
        Args:
            signal: Strategy signal
            
        Returns:
            Risk-reward ratio or None if not calculable
        """
        if not all([signal.entry_price, signal.stop_loss, signal.take_profit]):
            return None
        
        entry = float(signal.entry_price)
        stop = float(signal.stop_loss)
        target = float(signal.take_profit)
        
        risk = abs(entry - stop)
        reward = abs(target - entry)
        
        if risk == 0:
            return None
        
        return reward / risk
    
    def __repr__(self) -> str:
        return f"{self.name} ({self.strategy_type}, {self.allocation}% allocation)"






