"""
Core data models for the Market Adaptive Trading Bot.

This module defines all the fundamental data structures used throughout the trading bot system.
It includes market data models, trading signals, timeframes, and various analysis results.

The models are designed to be:
- Type-safe with proper type hints
- Immutable where appropriate using dataclasses
- Serializable for database storage and API communication
- Extensible for future enhancements

Key Components:
- MarketCondition: Enumeration of different market states
- TradeSignal: Enumeration of trading signals (BUY/SELL/HOLD)
- TimeFrame: Enumeration of supported trading timeframes
- CandleData: OHLCV market data structure
- TechnicalIndicators: Technical analysis results
- TradeRecommendation: Trading recommendations from analysis
- TradeDecision: Final trading decisions with risk management
- MarketContext: Comprehensive market state information
- TradeExecution: Trade execution details and results

Author: Trading Bot Development Team
Version: 2.0.0
Last Updated: 2024
"""
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Dict, List, Optional, Union, Any
from decimal import Decimal
import uuid

# Import debugging utilities
from trading_bot.src.utils.debug_utils import (
    debug_tracker, debug_line, debug_variable, debug_context, 
    debug_performance, debug_data_flow, debug_api_call, 
    debug_trade_decision, debug_strategy_execution, debug_risk_calculation,
    debug_indicator_calculation, debug_backtest_step, debug_entry_point,
    debug_exit_point, debug_conditional, debug_loop_iteration,
    get_debug_summary, export_debug_report
)


class MarketCondition(Enum):
    """
    Market condition types representing different market states.
    
    These conditions help the bot adapt its trading strategy based on current
    market behavior and volatility patterns.
    
    Attributes:
        NEWS_REACTIONARY: Market reacting to news events with high volatility
        REVERSAL: Market showing signs of trend reversal
        BREAKOUT: Market breaking through key support/resistance levels
        RANGING: Market moving sideways within a range
        UNKNOWN: Market condition cannot be determined
    """
    NEWS_REACTIONARY = "news_reactionary"
    REVERSAL = "reversal"
    BREAKOUT = "breakout"
    RANGING = "ranging"
    UNKNOWN = "unknown"


class TradeSignal(Enum):
    """
    Trade signal types for buy/sell/hold decisions.
    
    These signals are generated by technical analysis and used by the
    decision layer to make trading decisions.
    
    Attributes:
        BUY: Signal to enter a long position
        SELL: Signal to enter a short position
        HOLD: Signal to maintain current position or wait
    """
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class TimeFrame(Enum):
    """
    Trading timeframes supported by the bot.
    
    Multiple timeframes are used for multi-timeframe analysis to get
    a comprehensive view of market trends and signals.
    
    Attributes:
        M1: 1-minute timeframe
        M5: 5-minute timeframe
        M15: 15-minute timeframe
        M30: 30-minute timeframe
        H1: 1-hour timeframe
        H4: 4-hour timeframe
        D1: Daily timeframe
    """
    M1 = "M1"
    M5 = "M5"
    M15 = "M15"
    M30 = "M30"
    H1 = "H1"
    H4 = "H4"
    D1 = "D1"


@dataclass
class CandleData:
    """
    OHLCV (Open, High, Low, Close, Volume) candle data structure.
    
    This represents a single candlestick/bar of market data for a specific
    currency pair and timeframe. All price values are stored as Decimal
    for precise financial calculations.
    
    Attributes:
        timestamp: The timestamp when this candle period started
        open: Opening price of the candle period
        high: Highest price during the candle period
        low: Lowest price during the candle period
        close: Closing price of the candle period
        volume: Trading volume (optional, not always available for forex)
        pair: Currency pair symbol (e.g., 'EUR_USD')
        timeframe: Timeframe this candle represents (e.g., TimeFrame.M5)
    
    Note:
        The __post_init__ method automatically converts int/float values
        to Decimal for precise financial calculations.
    """
    timestamp: datetime
    open: Decimal
    high: Decimal
    low: Decimal
    close: Decimal
    volume: Optional[Decimal] = None
    pair: str = ""
    timeframe: TimeFrame = TimeFrame.M5
    
    def __post_init__(self):
        """Convert numeric values to Decimal for precise calculations."""
        debug_entry_point("CandleData.__post_init__")
        
        with debug_context("CandleData initialization") as context:
            debug_variable("original_open", self.open, context)
            debug_variable("original_high", self.high, context)
            debug_variable("original_low", self.low, context)
            debug_variable("original_close", self.close, context)
            debug_variable("original_volume", self.volume, context)
            debug_variable("pair", self.pair, context)
            debug_variable("timeframe", self.timeframe.value if self.timeframe else None, context)
            
            if isinstance(self.open, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "open_price")
                self.open = Decimal(str(self.open))
                debug_variable("converted_open", self.open, context)
            if isinstance(self.high, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "high_price")
                self.high = Decimal(str(self.high))
                debug_variable("converted_high", self.high, context)
            if isinstance(self.low, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "low_price")
                self.low = Decimal(str(self.low))
                debug_variable("converted_low", self.low, context)
            if isinstance(self.close, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "close_price")
                self.close = Decimal(str(self.close))
                debug_variable("converted_close", self.close, context)
            if self.volume and isinstance(self.volume, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "volume")
                self.volume = Decimal(str(self.volume))
                debug_variable("converted_volume", self.volume, context)
            
            debug_variable("candle_initialization_complete", True, context)
            debug_exit_point("CandleData.__post_init__")


@dataclass
class TechnicalIndicators:
    """
    Technical analysis indicators container.
    
    This class holds all calculated technical indicators for a currency pair
    at a specific point in time. It includes trend indicators, momentum
    oscillators, volatility measures, and support/resistance levels.
    
    Core Indicators:
        rsi: Relative Strength Index (0-100, overbought/oversold)
        macd: MACD line (trend following momentum indicator)
        macd_signal: MACD signal line (9-period EMA of MACD)
        macd_histogram: MACD histogram (MACD - Signal)
        ema_fast: Fast Exponential Moving Average (typically 12-period)
        ema_slow: Slow Exponential Moving Average (typically 26-period)
        atr: Average True Range (volatility measure)
        stoch_k: Stochastic %K (momentum oscillator)
        stoch_d: Stochastic %D (3-period SMA of %K)
    
    Volatility Indicators:
        bollinger_upper: Upper Bollinger Band
        bollinger_middle: Middle Bollinger Band (SMA)
        bollinger_lower: Lower Bollinger Band
        keltner_upper: Upper Keltner Channel
        keltner_lower: Lower Keltner Channel
        keltner_middle: Middle Keltner Channel (EMA)
    
    Support/Resistance:
        support_level: Key support price level
        resistance_level: Key resistance price level
    
    All values are optional and may be None if insufficient data is available
    for calculation or if the indicator is not configured.
    """
    # Core indicators
    rsi: Optional[float] = None
    macd: Optional[float] = None
    macd_signal: Optional[float] = None
    macd_histogram: Optional[float] = None
    ema_fast: Optional[float] = None
    ema_slow: Optional[float] = None
    bollinger_upper: Optional[float] = None
    bollinger_middle: Optional[float] = None
    bollinger_lower: Optional[float] = None
    atr: Optional[float] = None
    stoch_k: Optional[float] = None
    stoch_d: Optional[float] = None
    support_level: Optional[float] = None
    resistance_level: Optional[float] = None
    
    # Keltner Channels from custom indicators
    keltner_upper: Optional[float] = None
    keltner_lower: Optional[float] = None
    keltner_middle: Optional[float] = None
    
    # Bollinger Bands components
    bb_ma: Optional[float] = None  # Bollinger Bands Moving Average
    
    # RSI with period
    rsi_14: Optional[float] = None  # RSI with 14-period
    
    # MACD components
    macd_line: Optional[float] = None  # MACD line
    macd_signal_line: Optional[float] = None  # Signal line
    macd_histogram_line: Optional[float] = None  # Histogram


@dataclass
class MarketContext:
    """
    Market context and sentiment data container.
    
    This class holds comprehensive market state information including
    market conditions, volatility measures, trend analysis, news sentiment,
    and economic events that may affect trading decisions.
    
    Attributes:
        condition: Current market condition (ranging, breakout, etc.)
        volatility: Current market volatility level (0.0-1.0)
        trend_strength: Strength of current trend (0.0-1.0)
        news_sentiment: Overall news sentiment score (0.0-1.0, 0.5=neutral)
        economic_events: List of upcoming/recent economic events
        key_levels: Dictionary of important support/resistance levels
        timestamp: When this market context was captured
    
    The market context is used by the decision layer to make informed
    trading decisions based on current market conditions.
    """
    condition: MarketCondition = MarketCondition.UNKNOWN
    volatility: float = 0.0
    trend_strength: float = 0.0
    news_sentiment: float = 0.0
    economic_events: List[Dict[str, Any]] = field(default_factory=list)
    key_levels: Dict[str, float] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class TradeRecommendation:
    """
    Trade recommendation generated by technical analysis.
    
    This class represents a trading recommendation generated by the technical
    analysis layer. It includes all the necessary information for making a
    trading decision including entry/exit levels, risk management parameters,
    and confidence metrics.
    
    Attributes:
        id: Unique identifier for this recommendation
        pair: Currency pair symbol (e.g., 'EUR_USD')
        signal: Trading signal (BUY/SELL/HOLD)
        entry_price: Recommended entry price
        stop_loss: Recommended stop loss level
        take_profit: Recommended take profit level
        confidence: Confidence level of the recommendation (0.0-1.0)
        market_condition: Current market condition when recommendation was made
        reasoning: Human-readable explanation of the recommendation
        risk_reward_ratio: Calculated risk-to-reward ratio
        estimated_hold_time: Expected duration of the trade
        timestamp: When this recommendation was generated
        technical_analysis: Technical indicators used in the analysis
        market_context: Market context when recommendation was made
    
    The recommendation is passed to the decision layer for final approval
    and risk management adjustments.
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    pair: str = ""
    signal: TradeSignal = TradeSignal.HOLD
    entry_price: Optional[Decimal] = None
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    confidence: float = 0.0
    market_condition: MarketCondition = MarketCondition.UNKNOWN
    reasoning: str = ""
    risk_reward_ratio: float = 0.0
    estimated_hold_time: timedelta = timedelta(minutes=30)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    technical_analysis: Optional[TechnicalIndicators] = None
    market_context: Optional[MarketContext] = None
    
    def __post_init__(self):
        """Convert numeric values to Decimal for precise calculations."""
        debug_entry_point("TradeRecommendation.__post_init__")
        
        with debug_context("TradeRecommendation initialization") as context:
            debug_variable("recommendation_id", self.id, context)
            debug_variable("pair", self.pair, context)
            debug_variable("signal", self.signal.value if self.signal else None, context)
            debug_variable("original_entry_price", self.entry_price, context)
            debug_variable("original_stop_loss", self.stop_loss, context)
            debug_variable("original_take_profit", self.take_profit, context)
            debug_variable("confidence", self.confidence, context)
            debug_variable("market_condition", self.market_condition.value if self.market_condition else None, context)
            
            if isinstance(self.entry_price, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "entry_price")
                self.entry_price = Decimal(str(self.entry_price))
                debug_variable("converted_entry_price", self.entry_price, context)
            if isinstance(self.stop_loss, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "stop_loss")
                self.stop_loss = Decimal(str(self.stop_loss))
                debug_variable("converted_stop_loss", self.stop_loss, context)
            if isinstance(self.take_profit, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "take_profit")
                self.take_profit = Decimal(str(self.take_profit))
                debug_variable("converted_take_profit", self.take_profit, context)
            
            debug_variable("recommendation_initialization_complete", True, context)
            debug_exit_point("TradeRecommendation.__post_init__")


@dataclass
class TradeDecision:
    """
    Final trade decision after risk management processing.
    
    This class represents the final trading decision after the recommendation
    has been processed by the risk management layer. It includes the original
    recommendation plus any modifications made for risk management purposes.
    
    Attributes:
        recommendation: Original trade recommendation from technical analysis
        approved: Whether the trade has been approved for execution
        position_size: Calculated position size based on risk management
        risk_amount: Maximum amount of capital at risk for this trade
        modified_stop_loss: Stop loss level adjusted by risk management
        modified_take_profit: Take profit level adjusted by risk management
        risk_management_notes: Notes about risk management decisions made
        timestamp: When this decision was finalized
    
    The decision layer may modify the original recommendation based on:
    - Current portfolio exposure
    - Risk management rules
    - Market volatility conditions
    - Available capital
    """
    recommendation: TradeRecommendation
    approved: bool = False
    position_size: Optional[Decimal] = None
    risk_amount: Optional[Decimal] = None
    modified_stop_loss: Optional[Decimal] = None
    modified_take_profit: Optional[Decimal] = None
    risk_management_notes: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class NotificationMessage:
    """
    Notification message structure for user communications.
    
    This class represents messages sent to users via various notification
    channels (Telegram, email, etc.) about trading activities, alerts,
    and system status updates.
    
    Attributes:
        id: Unique identifier for this notification
        title: Short title/summary of the notification
        message: Detailed message content
        trade_decision: Associated trade decision (if applicable)
        chart_data: Chart/image data to include with notification
        buttons: Interactive buttons for user responses
        priority: Message priority level (low, normal, high, urgent)
        timestamp: When this notification was created
    
    Used by the notification layer to send structured messages to users.
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    title: str = ""
    message: str = ""
    trade_decision: Optional[TradeDecision] = None
    chart_data: Optional[Dict[str, Any]] = None
    buttons: List[Dict[str, str]] = field(default_factory=list)
    priority: str = "normal"  # low, normal, high, urgent
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class UserResponse:
    """
    User response to trade notification.
    
    This class captures user responses to trade notifications, including
    accept/edit/deny actions and any modifications made to trade parameters.
    
    Attributes:
        notification_id: ID of the notification being responded to
        action: User action (accept, edit, deny)
        user_id: ID of the user responding
        timestamp: When the response was received
        modified_params: Any trade parameters modified by the user
        notes: Additional notes from the user
    
    Used by the notification layer to process user feedback and actions.
    """
    notification_id: str
    action: str  # accept, edit, deny
    user_id: str
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    modified_params: Optional[Dict[str, Any]] = None
    notes: str = ""


@dataclass
class TradeExecution:
    """
    Trade execution details and results.
    
    This class represents the actual execution of a trade decision,
    including the execution price, timing, and broker response.
    
    Attributes:
        trade_decision: The original trade decision that was executed
        execution_price: Actual price at which the trade was executed
        execution_time: When the trade was executed
        trade_id: Broker-assigned trade ID (if available)
        broker_response: Full response from the broker API
        status: Current status of the trade execution
    
    Status values:
        - pending: Trade order submitted but not yet filled
        - filled: Trade order successfully executed
        - cancelled: Trade order was cancelled
        - rejected: Trade order was rejected by broker
    """
    trade_decision: TradeDecision
    execution_price: Decimal
    execution_time: datetime
    trade_id: Optional[str] = None
    broker_response: Optional[Dict[str, Any]] = None
    status: str = "pending"  # pending, filled, cancelled, rejected
    
    def __post_init__(self):
        """Convert numeric values to Decimal for precise calculations."""
        debug_entry_point("TradeExecution.__post_init__")
        
        with debug_context("TradeExecution initialization") as context:
            debug_variable("trade_id", self.trade_id, context)
            debug_variable("original_execution_price", self.execution_price, context)
            debug_variable("execution_time", self.execution_time, context)
            debug_variable("status", self.status, context)
            debug_variable("trade_decision_id", self.trade_decision.id if self.trade_decision else None, context)
            
            if isinstance(self.execution_price, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "execution_price")
                self.execution_price = Decimal(str(self.execution_price))
                debug_variable("converted_execution_price", self.execution_price, context)
            
            debug_variable("execution_initialization_complete", True, context)
            debug_exit_point("TradeExecution.__post_init__")


@dataclass
class PerformanceMetrics:
    """
    Trading performance metrics container.
    
    This class holds comprehensive trading performance statistics including
    trade counts, profit/loss metrics, risk measures, and performance ratios.
    Used for tracking bot performance over time and generating reports.
    
    Trade Statistics:
        total_trades: Total number of trades executed
        winning_trades: Number of profitable trades
        losing_trades: Number of losing trades
        win_rate: Percentage of winning trades (0.0-1.0)
    
    Profit/Loss Metrics:
        total_profit: Sum of all profitable trades
        total_loss: Sum of all losing trades (absolute value)
        net_profit: Total profit minus total loss
        average_win: Average profit per winning trade
        average_loss: Average loss per losing trade
        profit_factor: Ratio of total profit to total loss
    
    Risk Metrics:
        max_drawdown: Maximum peak-to-trough decline
        sharpe_ratio: Risk-adjusted return measure
    
    Time Period:
        period_start: Start of the performance measurement period
        period_end: End of the performance measurement period
    
    All monetary values are stored as Decimal for precise calculations.
    """
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    win_rate: float = 0.0
    total_profit: Decimal = Decimal('0')
    total_loss: Decimal = Decimal('0')
    net_profit: Decimal = Decimal('0')
    max_drawdown: Decimal = Decimal('0')
    sharpe_ratio: float = 0.0
    average_win: Decimal = Decimal('0')
    average_loss: Decimal = Decimal('0')
    profit_factor: float = 0.0
    period_start: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    period_end: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    
    def __post_init__(self):
        """Convert numeric values to Decimal for precise calculations."""
        debug_entry_point("PerformanceMetrics.__post_init__")
        
        with debug_context("PerformanceMetrics initialization") as context:
            debug_variable("total_trades", self.total_trades, context)
            debug_variable("winning_trades", self.winning_trades, context)
            debug_variable("losing_trades", self.losing_trades, context)
            debug_variable("win_rate", self.win_rate, context)
            debug_variable("original_total_profit", self.total_profit, context)
            debug_variable("original_total_loss", self.total_loss, context)
            debug_variable("original_net_profit", self.net_profit, context)
            debug_variable("original_max_drawdown", self.max_drawdown, context)
            debug_variable("original_average_win", self.average_win, context)
            debug_variable("original_average_loss", self.average_loss, context)
            debug_variable("sharpe_ratio", self.sharpe_ratio, context)
            debug_variable("profit_factor", self.profit_factor, context)
            
            if isinstance(self.total_profit, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "total_profit")
                self.total_profit = Decimal(str(self.total_profit))
                debug_variable("converted_total_profit", self.total_profit, context)
            if isinstance(self.total_loss, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "total_loss")
                self.total_loss = Decimal(str(self.total_loss))
                debug_variable("converted_total_loss", self.total_loss, context)
            if isinstance(self.net_profit, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "net_profit")
                self.net_profit = Decimal(str(self.net_profit))
                debug_variable("converted_net_profit", self.net_profit, context)
            if isinstance(self.max_drawdown, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "max_drawdown")
                self.max_drawdown = Decimal(str(self.max_drawdown))
                debug_variable("converted_max_drawdown", self.max_drawdown, context)
            if isinstance(self.average_win, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "average_win")
                self.average_win = Decimal(str(self.average_win))
                debug_variable("converted_average_win", self.average_win, context)
            if isinstance(self.average_loss, (int, float)):
                debug_data_flow("decimal_conversion", "converting", "average_loss")
                self.average_loss = Decimal(str(self.average_loss))
                debug_variable("converted_average_loss", self.average_loss, context)
            
            debug_variable("performance_metrics_initialization_complete", True, context)
            debug_exit_point("PerformanceMetrics.__post_init__") 